# === Docker Compose for MedEdBot ===
# For production deployment (Render, Railway, Heroku, VPS)

version: '3.8'

services:
  mededbot:
    build: .
    container_name: mededbot
    restart: unless-stopped
    
    # Port mapping
    ports:
      - "${PORT:-8080}:8080"
    
    # Environment variables
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - CONTAINER_LOGGING=true  # Enable container-friendly logging
      - PYTHONUNBUFFERED=1  # Ensure unbuffered output for real-time logs
      # Add your actual environment variables here:
      # - LINE_CHANNEL_ACCESS_TOKEN=your_token
      # - LINE_CHANNEL_SECRET=your_secret
      # - GEMINI_API_KEY=your_key
      # - GMAIL_ADDRESS=your_email
      # - GMAIL_APP_PASSWORD=your_password
      # - R2_ENDPOINT_URL=https://your-account-id.r2.cloudflarestorage.com
      # - R2_ACCESS_KEY_ID=your_access_key
      # - R2_SECRET_ACCESS_KEY=your_secret_key
      # - R2_BUCKET_NAME=mededbot
      # - R2_PUBLIC_URL=https://your-domain.com
      # - BASE_URL=https://your-domain.com
      # For local development on Windows with WSL:
      # - BASE_URL=http://192.168.0.109:10001
    
    # Alternative: Load from .env file (recommended for Synology)
    env_file:
      - .env
    
    # Volume mounts for persistent data
    volumes:
      - ./data/tts_audio:/app/tts_audio
      - ./data/voicemail:/app/voicemail
      - ./data/logs:/app/logs
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    # Security options
    security_opt:
      - no-new-privileges:true
    
networks:
  default:
    driver: bridge