# === Docker Compose for Synology NAS ===
# Optimized for Synology Container Manager

version: '3.3'  # Use 3.3 for better Synology compatibility

services:
  mededbot:
    build: 
      context: .
      dockerfile: Dockerfile.synology
    container_name: mededbot
    restart: unless-stopped
    
    ports:
      - "10001:8080"
    
    environment:
      - PORT=8080
      - LOG_LEVEL=info
      - CONTAINER_LOGGING=true
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      # Synology-specific optimizations
      - MALLOC_TRIM_THRESHOLD_=100000
      - PYTHONOPTIMIZE=1
      - USE_MEMORY_STORAGE=false
    
    env_file:
      - .env
    
    volumes:
      - ./data/tts_audio:/app/tts_audio
      - ./data/voicemail:/app/voicemail
      - ./data/logs:/app/logs
    
    # Simple health check for Synology
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:8080/health', timeout=10)"]
      interval: 120s
      timeout: 30s
      retries: 3
      start_period: 60s
    
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    security_opt:
      - no-new-privileges:true
    
    # IMPORTANT: Disable TTY for Synology Container Manager logs
    tty: false
    stdin_open: false
    

networks:
  default:
    driver: bridge