version: '3.8'

services:
  mededbot:
    build: .
    container_name: mededbot
    restart: unless-stopped
    
    ports:
      - "${PORT:-10001}:10001"
    
    environment:
      - PORT=10001
      - LOG_LEVEL=info
      - CONTAINER_LOGGING=true
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
      # Synology-specific optimizations
      - MALLOC_TRIM_THRESHOLD_=100000
      - PYTHONOPTIMIZE=1
      - USE_MEMORY_STORAGE=false
    
    env_file:
      - .env
    
    volumes:
      - ./data/tts_audio:/app/tts_audio
      - ./data/voicemail:/app/voicemail
      - ./data/logs:/app/logs
    
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:10001/health"]
      interval: 120s
      timeout: 50s
      retries: 3
      start_period: 60s
    
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    
    security_opt:
      - no-new-privileges:true
    
    # IMPORTANT: Disable TTY for Synology Container Manager logs
    tty: false
    stdin_open: false
    
    # Simple uvicorn like the old stable version
    command: uvicorn main:app --host 0.0.0.0 --port 10001

networks:
  default:
    driver: bridge